# Generated by Django 2.1 on 2023-11-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20231009_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cultivated_species',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
