# Generated by Django 2.1 on 2023-11-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_cart_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=32)),
                ('password', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=32)),
                ('price', models.FloatField(default=0)),
                ('imgUrl', models.CharField(default='', max_length=2048)),
                ('status', models.CharField(default='', max_length=32)),
                ('remark', models.CharField(default='', max_length=2048)),
                ('source', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('imgUrl', models.CharField(default='', max_length=2048)),
                ('introduce', models.CharField(default='', max_length=2048)),
                ('detailUrl', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Illustrated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField(default=0)),
                ('introduce', models.CharField(default='', max_length=2048)),
                ('method', models.CharField(default='', max_length=2048)),
                ('detailUrl', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=32)),
                ('source', models.CharField(default='', max_length=32)),
                ('subject', models.CharField(default='', max_length=256)),
                ('info', models.CharField(default='', max_length=2048)),
                ('email', models.CharField(default='', max_length=256)),
                ('reply', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=32)),
                ('imgUrl', models.CharField(default='', max_length=256)),
                ('detailUrl', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=32)),
                ('password', models.CharField(default='', max_length=32)),
                ('telephone', models.CharField(default='', max_length=32)),
                ('identity', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='consignee',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
