# Generated by Django 2.1 on 2023-11-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20231107_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illustrated',
            old_name='detailUrl',
            new_name='diseasetype',
        ),
    ]
