# Generated by Django 3.2.23 on 2023-12-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20231112_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cultivated_species',
            new_name='species',
        ),
    ]
