# Generated by Django 3.2.23 on 2023-12-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_rename_cultivated_species_user_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oid',
        ),
    ]
