# Generated by Django 3.2.23 on 2023-12-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_remove_order_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='illustrated',
            name='did',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='rid',
        ),
    ]
