# Generated by Django 3.2.23 on 2023-12-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20231205_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustrated',
            name='img1',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='illustrated',
            name='img2',
            field=models.CharField(default='', max_length=128),
        ),
    ]
